[start]
visual-home = "cgi-bin:chabookmark?action=view"

[buffer]
images = true

[display]
image-mode = "kitty"

[[siteconf]]
url = 'https://merveilles\.town/.*'
cookie = "save"
scription = "app"

[[siteconf]]
url = 'http://localhost:8384/.*'
cookie = 'save'
scripting = 'app'

[[siteconf]]
url = 'https://meta\.sr\.ht/.*'
cookie = 'save'
scripting = 'app'


[[siteconf]]
url = 'https://git\.sr\.ht/.*'
cookie = 'save'
scripting = 'app'

[[siteconf]]
url = 'https://meta\.sr\.ht/.*'
cookie = 'save'
scripting = 'app'

[[siteconf]]
url = 'https://sr\.ht/.*'
cookie = 'save'
scripting = 'app'

[[siteconf]]
url = 'https://compudanzas\.itch\.io/.*'
scripting = 'app'
